Repository PovarIsSFEDU/teamerPD, pull requests merged in 2021-12, with the labels that each got.

#5 Added file upload
  src/auth/token/mod.rs
  src/auth/validator.rs
  src/crypto/mod.rs
  src/database/dbinsert.rs
  src/database/mod.rs
  src/database/mongo.rs
  src/database/new_user.rs
  src/database/team.rs
  src/database/user.rs
  src/lib.rs
  src/main.rs
  src/prelude/concat.rs
  src/prelude/mod.rs
  src/routes/api/helpers.rs
  src/routes/api/mod.rs
  src/routes/pages/mod.rs
Labels: Backend, QA: approved

#7 Mailing2
  Cargo.lock
  Cargo.toml
  src/auth/token/mod.rs
  src/mail/mod.rs
  src/main.rs
  src/prelude/mod.rs
  src/routes/api/mod.rs
Labels: QA: needs testing, Backend

#6 Feature20
  resources/templates/profile.html.tera
  src/database/mod.rs
  src/database/mongo.rs
  src/database/team.rs
  src/database/user.rs
  src/main.rs
  src/routes/api/mod.rs
  src/teams/mod.rs
Labels: Backend, QA: testing

#11 Feature19
  resources/css/colors.css
  resources/css/emailverified.css
  resources/css/main.css
  resources/css/teams.css
  resources/js/emailverified.js
  resources/js/teams.js
  resources/templates/emailverified.html
  resources/templates/main.html.tera
  resources/templates/profile.html.tera
  resources/templates/team.html
  resources/templates/teams.html
  src/main.rs
  src/routes/api/mod.rs
  src/routes/pages/mod.rs
Labels: Frontend, QA: testing

#12 Hotfix#1 (teamer#31)
  resources/css/about.css
  resources/css/login.css
  resources/css/profile.css
  resources/js/login.js
  resources/js/profile.js
  resources/js/sendRequest.js
  resources/photos/Alex.jpg
  resources/photos/Denis.jpg
  resources/photos/Dmitry.jpg
  resources/photos/Ilya.jpg
  resources/photos/Nastya.jpg
  resources/photos/Pavel.jpg
  resources/photos/Tigran.jpg
  resources/templates/about.html.tera
  resources/templates/login.html
  resources/templates/profile.html.tera
  resources/templates/teams.html.tera
  src/auth/token/mod.rs
  src/database/mod.rs
  src/database/mongo.rs
  src/database/user.rs
  src/main.rs
  src/routes/api/mod.rs
  src/routes/pages/mod.rs
Labels: Frontend, QA: approved
